### ISSUE TITLE
run's default progress bar behaviour differs from nengo

### ISSUE THREAD

**Issue by arvoelke** [nengo/nengo-dl#105]
Just a very minor inconvenience when switching between Nengo and Nengo-DL. In Nengo, the default for `sim.run` and `sim.run_steps` is `progress_bar=None` which inherits the progress bar from the constructor. But in Nengo-DL the default is `progress_bar=True`. This means I need to disable the progress bar in 2 places rather than 1.

**Comment by drasmuss** [comment]
Fixed in https://github.com/nengo/nengo-dl/pull/113
