### ISSUE TITLE
Reopening the simulator raises an obscure error

### ISSUE THREAD

**Issue by arvoelke** [nengo/nengo-dl#115]
Version: `master`

### Minimal reproducer
```python
sim = nengo_dl.Simulator(nengo.Network())
with sim:
    pass
with sim:
    pass
```

### Stack trace
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-12-f89be4cbbd16> in <module>
      2 with sim:
      3     pass
----> 4 with sim:
      5     pass

~/git/nengo-dl/nengo_dl/simulator.py in __enter__(self)
   1905 
   1906     def __enter__(self):
-> 1907         self._graph_context = self.graph.as_default()
   1908         self._device_context = self.graph.device(self.tensor_graph.device)
   1909 

AttributeError: 'NoneType' object has no attribute 'as_default'
```

### Expected behaviour
Would expect either to be able to reopen the simulator (IMO useful for interactively coding in jupyter), or to get a more informative error message.

**Comment by tbekolay** [comment]
Reopening the simulator is definitely not a use case we can support on all backends, so I don't think any backend should allow it. A more informative error message seems appropriate though.

**Comment by drasmuss** [comment]
We should probably add a test for this in Nengo core as well (asserting that you can't reopen a closed Simulator).
