### ISSUE TITLE
spiking-mnist

### ISSUE THREAD

**Issue by Amri95** [nengo/nengo-dl#180]
I am using nengo-dl version 3.0

while running the code : 
**minibatch_size = 100
sim = nengo_dl.Simulator(net, minibatch_size=minibatch_size)**

I am getting this TypeError:
**TypeError: finish() got an unexpected keyword argument 'dirty'**

**Comment by drasmuss** [comment]
Your `progressbar2` version is incompatible with your `nengo-dl` version. You can either upgrade `nengo-dl` to a more recent version (>=3.1.0), or downgrade `progressbar2` (<3.50.0).

**Comment by Amri95** [comment]
Thank you so much.
