### ISSUE TITLE
 Process finished with exit code 132 (interrupted by signal 4: SIGILL) on import on Apple Silicon

### ISSUE THREAD

**Issue by Tioz90** [nengo/nengo-dl#188]
I was hoping to test nengo-dl's performance on a new Mac mini with Apple Silicon but I'm getting the following error every time I try `import nengo_dl`:

`Process finished with exit code 132 (interrupted by signal 4: SIGILL)`

**Comment by drasmuss** [comment]
Can you run regular tensorflow models (not using NengoDL)?
