### ISSUE TITLE
`nengo_dl` cannot import `keras.engine`

### ISSUE THREAD

**Issue by taylor-curley** [nengo/nengo-dl#236]
Hi all,

I am having trouble running `nengo_dl` code using Anaconda; specifically, it returns this error message:

```
In [1]:  import nengo_dl
Traceback (most recent call last):

  Cell In[1], line 9
    import nengo_dl

  File D:\anaconda3\Lib\site-packages\nengo_dl\__init__.py:16
    from nengo_dl import (

  File D:\anaconda3\Lib\site-packages\nengo_dl\op_builders.py:25
    from nengo_dl.compat import SimProbe

  File D:\anaconda3\Lib\site-packages\nengo_dl\compat.py:174
    from keras.engine.functional import Functional, _build_map

ModuleNotFoundError: No module named 'keras.engine'
```

Any recommendations on how to fix this issue? Thank you!

**Comment by skim0119** [comment]
@taylor-curley I have a temporary solution for recent version of keras/tensorflow: 
https://github.com/skim0119/nengo-dl/blob/f8bf2c434a67f49af81cc301144cd881a74f4c5e/nengo_dl/compat.py#L74-L77

**Comment by taylor-curley** [comment]
Thank you! This works - I'll close this out here.
