### ISSUE TITLE
sim.loss issue : "ValidationError: input data: should have rank 3 (batch_size, n_steps, dimensions), found rank 4"

### ISSUE THREAD

**Issue by joh10891** [nengo/nengo-dl#71]
I'm attempting to run the spiking_mnist demo with mnist fashion dataset instead of digits, but am getting a `"ValidationError: input data: should have rank 3 (batch_size, n_steps, dimensions), found rank 4" ` error when running `sim.loss`. I converted to one-hot, and it seems to be the exact same format as the mnist example. What could the rank issue be? Running digits seems to work, but the clothing mnist fails
<img width="599" alt="screen shot 2018-11-18 at 4 49 30 pm" src="https://user-images.githubusercontent.com/29440741/48679142-03e53a00-eb52-11e8-91d9-390f3acbe9c0.png">

**Comment by joh10891** [comment]
That is what I had assumed, but when I `  print("x_train shape:", x_train.shape, "y_train shape:", y_train.shape) ` , it returns `x_train shape: (60000, 28, 28) y_train shape: (60000,)` So it appears that the x_train is 3 dim.

**Comment by drasmuss** [comment]
Oh also keep in mind that if you're following the [spiking-mnist example](https://www.nengo.ai/nengo-dl/examples/spiking-mnist.html) then later on you're adding an extra dimension (for time), so your shape would become `(60000, 1, 28, 28)`.

**Comment by joh10891** [comment]
Ah, yes. Attached are some tests I ran after loading both datasets (prior to adding the time dimension). They seem so similar (screenshot), so was not sure why the mnist fashion would throw an extra dimension error when running sim. After poring through data very thoroughly, was able to sort it out- issue was with each row in mnist fashion image being stored as an array, rather than one large array.

After restructuring data, got spiking working with fashion-mnist! I appreciate the help!
<img width="375" alt="screen shot 2018-11-18 at 10 58 50 pm" src="https://user-images.githubusercontent.com/29440741/48689134-b935e300-eb8e-11e8-8b9a-80e46fdbf761.png">

**Comment by sauravtii** [comment]
Hi @joh10891!

I am also facing the same issue, so can you please share the code of how you restructured the data that helped you resolving the issue ?
