### ISSUE TITLE
Support for tf.data input pipelines

### ISSUE THREAD

**Issue by hunse** [nengo/nengo-dl#75]
I was just reading [this page](https://www.tensorflow.org/guide/performance/overview#data_formats), and it recommends not using `feed_dict` with `sess.run`, since apparently it's often slow. This is how `nengo_dl` currently does things.

The first step is to determine if this is actually a problem in `nengo_dl`, by benchmarking the `feed_dict` method versus other alternatives (I'm not sure what alternatives there all are).

**Comment by drasmuss** [comment]
This was added in https://github.com/nengo/nengo-dl/pull/95, you can now use `tf.data` input piplines with any of the `predict`/`fit`/`evaluate` methods.
