### ISSUE TITLE
freeze_params makes the network unpicklable

### ISSUE THREAD

**Issue by arvoelke** [nengo/nengo-dl#93]
**Minimal Reproducer**

```python
do_bug = True

import pickle
import nengo
import nengo_dl

with nengo.Network() as model:
    nengo.Ensemble(100, 1)

with nengo_dl.Simulator(model) as sim:
    if do_bug:
        sim.freeze_params(model)
    
s = pickle.dumps(model)
pickle.loads(s)
```

**Error**

```
ValidationError                           Traceback (most recent call last)
<ipython-input-12-6a0fd89abc6d> in <module>()
     13 
     14 s = pickle.dumps(model)
---> 15 pickle.loads(s)

~/git/nengo/nengo/base.py in __setstate__(self, state)
     89         for attr in self.params:
     90             if attr in state:
---> 91                 setattr(self, attr, state.pop(attr))
     92 
     93         for k, v in state.items():

~/git/nengo/nengo/base.py in __setattr__(self, name, val)
    105                 "Did you mean to change an existing attribute?" % (name, self),
    106                 SyntaxWarning)
--> 107         super().__setattr__(name, val)
    108 
    109     def __str__(self):

~/git/nengo/nengo/config.py in __setattr__(self, name, val)
    453             except ValidationError:
    454                 exc_info = sys.exc_info()
--> 455                 raise exc_info[1].with_traceback(None)
    456         else:
    457             super().__setattr__(name, val)

ValidationError: Ensemble.n_neurons: Unconfigurable parameters have no defaults. Please ensure the value of the parameter is set before trying to access it.
```

**Expected Behaviour**

I expect to be able to unpickle the model. The reason I am using `freeze_params` here is so that I can save a trained `nengo_dl` model and then run the same model later on a different backend. The work-around is to keep the trained model in memory, and avoid pickling it between training and testing. This however means that I need to retrain the model every time that I want to test it. The work-around for this is to manually save all of the parameters for each layer and then manually reconstruct the model later.

**Versions**

Current master branch on both `nengo` and `nengo_dl`.

**Comment by drasmuss** [comment]
I'll take a look into the pickling behaviour, but if you want a way to do this for now that doesn't rely on pickling you can use the `sim.save/load_params` functions (which will save the parameters in a TensorFlow format, rather than through pickle).  E.g.

``` python
net = build_network()
with nengo_dl.Simulator(net) as sim:
    sim.train(...)
    sim.save_params("my_params")
```
then to load them into a different backend
```
net = build_network()
with nengo_dl.Simulator(net) as sim:
    sim.load_params("my_params")
    sim.freeze_params()

with another_backend.Simulator(net) as sim:
    ...
```

**Comment by arvoelke** [comment]
Oh neat. I was aware of those other methods but hadn't thought to combine them with the approach here. That should be good for now, thanks!

**Comment by drasmuss** [comment]
Might be fixed in https://github.com/nengo/nengo/pull/1584?

**Comment by drasmuss** [comment]
Confirmed that this is resolved by the above fix in nengo core. That change hasn't yet made its way into a nengo core release, so anyone running into this issue should check out the development version of nengo core (3.1.0).
